### ISSUE TITLE
crash on 5.0.1

### ISSUE THREAD

**Issue by lvaccaro** [RCasatta/EternityWallAndroid#28]
suspending with open popup menu, and then resume the app with opened popup menu.

12-10 18:21:57.551      572-605/? A/WindowAnimator﹕ Unhandled exception in Window Manager
    java.lang.NullPointerException: mNativeObject is null. Have you called release() already?
            at android.view.SurfaceControl.checkNotReleased(SurfaceControl.java:342)
            at android.view.SurfaceControl.setPosition(SurfaceControl.java:372)
            at com.android.server.wm.AppWindowAnimator.stepThumbnailAnimation(AppWindowAnimator.java:200)
            at com.android.server.wm.AppWindowAnimator.stepAnimationLocked(AppWindowAnimator.java:273)
            at com.android.server.wm.WindowAnimator.updateAppWindowsLocked(WindowAnimator.java:187)
            at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:569)
            at com.android.server.wm.WindowAnimator.access$000(WindowAnimator.java:52)
            at com.android.server.wm.WindowAnimator$1.run(WindowAnimator.java:121)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:549)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.android.server.ServiceThread.run(ServiceThread.java:46)

**Comment by mgood7123** [comment]
oof why close with no comments?
