### ISSUE TITLE
Play Crash Report

### ISSUE THREAD

**Issue by RCasatta** [RCasatta/EternityWallAndroid#59]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
	at android.widget.ArrayAdapter.init(ArrayAdapter.java:310)
	at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:153)
	at it.eternitywall.eternitywall.adapters.MessageListAdapter.<init>(MessageListAdapter.java:41)
	at it.eternitywall.eternitywall.fragments.ListFragment$3.onPostExecute(ListFragment.java:229)
	at android.os.AsyncTask.finish(AsyncTask.java:632)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5272)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)

**Comment by lvaccaro** [comment]
error is caused by super line:

public MessageListAdapter(Activity activity, int resource, List<Message> objects, Integer inQueue, MessageListAdapterManager manager) {
        super(activity, resource, objects);
    
this object is called in ListFragment:
MessageListAdapter messageListAdapter = new MessageListAdapter(getActivity(), R.layout.item_message, messages, inQueue, ListFragment.this);
                        
So something of these parameters is null : getActivity(), R.layout.item_message, messages .
Do you know the device?
